### ISSUE TITLE
Executing mapping file gives "Invalid JSON-LD syntax; a term cannot be an empty string."

### ISSUE THREAD

**Issue by pheyvaer** [semantifyit/RocketRML#7]
If I use the mapping file with the input JSON file below, I get the following error:

```
JsonLdError [jsonld.SyntaxError]: Invalid JSON-LD syntax; a term cannot be an empty string.
    at Object.api.createTermDefinition (/home/pieter/Developer/RocketRML/node_modules/jsonld/lib/context.js:325:11)
    at api.process (/home/pieter/Developer/RocketRML/node_modules/jsonld/lib/context.js:265:11)
    at /home/pieter/Developer/RocketRML/node_modules/jsonld/lib/jsonld.js:942:10
    at async Function.processContext (/home/pieter/Developer/RocketRML/node_modules/jsonld/lib/util.js:460:16)
    at async /home/pieter/Developer/RocketRML/node_modules/jsonld/lib/jsonld.js:168:21
    at async Function.compact (/home/pieter/Developer/RocketRML/node_modules/jsonld/lib/util.js:460:16)
    at async quadsToJsonLD (/home/pieter/Developer/RocketRML/src/mapfile/mapfileParser.js:9:9)
    at async Object.expandedJsonMap (/home/pieter/Developer/RocketRML/src/mapfile/mapfileParser.js:84:20) {
  name: 'jsonld.SyntaxError',
  details: {
    code: 'invalid term definition',
    context: {
      rr: 'http://www.w3.org/ns/r2rml#',
      rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
      rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
      fnml: 'http://semweb.mmlab.be/ns/fnml#',
      fno: 'https://w3id.org/function/ontology#',
      d2rq: 'http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#',
      rml: 'http://semweb.mmlab.be/ns/rml#',
      ql: 'http://semweb.mmlab.be/ns/ql#',
      '': 'http://mapping.example.com/',
      ex: 'http://example.org/'
    }
  }
}
```
 The mapping file contains:
```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#>.
@prefix fno: <https://w3id.org/function/ontology#>.
@prefix d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix : <http://mapping.example.com/>.
@prefix ex: <http://example.org/>.

:map_senior_0 rml:logicalSource :source_0.
:source_0 a rml:LogicalSource;
    rml:source "example.json";
    rml:iterator "$";
    rml:referenceFormulation ql:JSONPath.
:map_senior_0 a rr:TriplesMap;
    rdfs:label "senior".
:s_0 a rr:SubjectMap.
:map_senior_0 rr:subjectMap :s_0.
:s_0 rr:template "http://example.org/{id}".
:pom_0 a rr:PredicateObjectMap.
:map_senior_0 rr:predicateObjectMap :pom_0.
:pm_0 a rr:PredicateMap.
:pom_0 rr:predicateMap :pm_0.
:pm_0 rr:constant ex:test.
:pom_0 rr:objectMap :om_0.
:om_0 a rr:ObjectMap;
    rml:reference "test";
    rr:termType rr:Literal;
    rr:datatype <http://www.w3.org/2001/XMLSchema#date>.
```
 The JSON file `example.json` contains
```
{
  "id": "John",
  "test": "1950-03-27"  
}
```

**Comment by ThibaultGerrier** [comment]
Hey thanks for the report.
There was an issue compacting the mappingfile using the jsonld library with an empty string prefix.
The issue is now resolved. 
Your example now works in v1.0.3 and will produce the following:
```json
[
  {
    "@id": "http://example.org/John",
    "http://example.org/test": {
      "@value": "1950-03-27",
      "@type": "http://www.w3.org/2001/XMLSchema#date"
    }
  }
]
```
or in n3
```turtle
<http://example.org/John> <http://example.org/test> "1950-03-27"^^<http://www.w3.org/2001/XMLSchema#date> .
```

**Comment by pheyvaer** [comment]
Thanks! This works now :smile:
